import { RickAndMortyResponse } from '@src/types/ram-types';

export const cardData: RickAndMortyResponse = {
  info: {
    count: 321,
    pages: 17,
    next: 'https://rickandmortyapi.com/api/character/?page=2&name=m',
    prev: null,
  },
  results: [
    {
      id: 737,
      name: 'Cirque du Soleil Zumanity Member',
      status: 'Alive',
      species: 'Human',
      type: '',
      gender: 'Female',
      origin: {
        name: 'Near-Duplicate Reality',
        url: 'https://rickandmortyapi.com/api/location/104',
      },
      location: {
        name: 'Earth (Replacement Dimension)',
        url: 'https://rickandmortyapi.com/api/location/20',
      },
      image: 'https://rickandmortyapi.com/api/character/avatar/737.jpeg',
      episode: ['https://rickandmortyapi.com/api/episode/45'],
      url: 'https://rickandmortyapi.com/api/character/737',
      created: '2021-10-17T12:24:53.547Z',
    },
    {
      id: 728,
      name: 'Sperm Queen',
      status: 'Dead',
      species: 'unknown',
      type: 'Super Sperm Monster',
      gender: 'Female',
      origin: {
        name: 'Morty',
        url: 'https://rickandmortyapi.com/api/location/114',
      },
      location: {
        name: 'Earth (Replacement Dimension)',
        url: 'https://rickandmortyapi.com/api/location/20',
      },
      image: 'https://rickandmortyapi.com/api/character/avatar/728.jpeg',
      episode: ['https://rickandmortyapi.com/api/episode/45'],
      url: 'https://rickandmortyapi.com/api/character/728',
      created: '2021-10-17T10:12:05.246Z',
    },
    {
      id: 3,
      name: 'Summer Smith',
      status: 'Alive',
      species: 'Human',
      type: '',
      gender: 'Female',
      origin: {
        name: 'Earth (Replacement Dimension)',
        url: 'https://rickandmortyapi.com/api/location/20',
      },
      location: {
        name: 'Earth (Replacement Dimension)',
        url: 'https://rickandmortyapi.com/api/location/20',
      },
      image: 'https://rickandmortyapi.com/api/character/avatar/3.jpeg',
      episode: [
        'https://rickandmortyapi.com/api/episode/6',
        'https://rickandmortyapi.com/api/episode/7',
        'https://rickandmortyapi.com/api/episode/8',
        'https://rickandmortyapi.com/api/episode/9',
        'https://rickandmortyapi.com/api/episode/10',
        'https://rickandmortyapi.com/api/episode/11',
        'https://rickandmortyapi.com/api/episode/12',
        'https://rickandmortyapi.com/api/episode/14',
        'https://rickandmortyapi.com/api/episode/15',
        'https://rickandmortyapi.com/api/episode/16',
        'https://rickandmortyapi.com/api/episode/17',
        'https://rickandmortyapi.com/api/episode/18',
        'https://rickandmortyapi.com/api/episode/19',
        'https://rickandmortyapi.com/api/episode/20',
        'https://rickandmortyapi.com/api/episode/21',
        'https://rickandmortyapi.com/api/episode/22',
        'https://rickandmortyapi.com/api/episode/23',
        'https://rickandmortyapi.com/api/episode/24',
        'https://rickandmortyapi.com/api/episode/25',
        'https://rickandmortyapi.com/api/episode/26',
        'https://rickandmortyapi.com/api/episode/27',
        'https://rickandmortyapi.com/api/episode/29',
        'https://rickandmortyapi.com/api/episode/30',
        'https://rickandmortyapi.com/api/episode/31',
        'https://rickandmortyapi.com/api/episode/32',
        'https://rickandmortyapi.com/api/episode/33',
        'https://rickandmortyapi.com/api/episode/34',
        'https://rickandmortyapi.com/api/episode/35',
        'https://rickandmortyapi.com/api/episode/36',
        'https://rickandmortyapi.com/api/episode/38',
        'https://rickandmortyapi.com/api/episode/39',
        'https://rickandmortyapi.com/api/episode/40',
        'https://rickandmortyapi.com/api/episode/41',
        'https://rickandmortyapi.com/api/episode/42',
        'https://rickandmortyapi.com/api/episode/43',
        'https://rickandmortyapi.com/api/episode/44',
        'https://rickandmortyapi.com/api/episode/45',
        'https://rickandmortyapi.com/api/episode/46',
        'https://rickandmortyapi.com/api/episode/47',
        'https://rickandmortyapi.com/api/episode/48',
        'https://rickandmortyapi.com/api/episode/49',
        'https://rickandmortyapi.com/api/episode/51',
      ],
      url: 'https://rickandmortyapi.com/api/character/3',
      created: '2017-11-04T19:09:56.428Z',
    },
    {
      id: 4,
      name: 'Beth Smith',
      status: 'Alive',
      species: 'Human',
      type: '',
      gender: 'Female',
      origin: {
        name: 'Earth (Replacement Dimension)',
        url: 'https://rickandmortyapi.com/api/location/20',
      },
      location: {
        name: 'Earth (Replacement Dimension)',
        url: 'https://rickandmortyapi.com/api/location/20',
      },
      image: 'https://rickandmortyapi.com/api/character/avatar/4.jpeg',
      episode: [
        'https://rickandmortyapi.com/api/episode/6',
        'https://rickandmortyapi.com/api/episode/7',
        'https://rickandmortyapi.com/api/episode/8',
        'https://rickandmortyapi.com/api/episode/9',
        'https://rickandmortyapi.com/api/episode/10',
        'https://rickandmortyapi.com/api/episode/11',
        'https://rickandmortyapi.com/api/episode/12',
        'https://rickandmortyapi.com/api/episode/14',
        'https://rickandmortyapi.com/api/episode/15',
        'https://rickandmortyapi.com/api/episode/16',
        'https://rickandmortyapi.com/api/episode/18',
        'https://rickandmortyapi.com/api/episode/19',
        'https://rickandmortyapi.com/api/episode/20',
        'https://rickandmortyapi.com/api/episode/21',
        'https://rickandmortyapi.com/api/episode/22',
        'https://rickandmortyapi.com/api/episode/23',
        'https://rickandmortyapi.com/api/episode/24',
        'https://rickandmortyapi.com/api/episode/25',
        'https://rickandmortyapi.com/api/episode/26',
        'https://rickandmortyapi.com/api/episode/27',
        'https://rickandmortyapi.com/api/episode/28',
        'https://rickandmortyapi.com/api/episode/29',
        'https://rickandmortyapi.com/api/episode/30',
        'https://rickandmortyapi.com/api/episode/31',
        'https://rickandmortyapi.com/api/episode/32',
        'https://rickandmortyapi.com/api/episode/33',
        'https://rickandmortyapi.com/api/episode/34',
        'https://rickandmortyapi.com/api/episode/35',
        'https://rickandmortyapi.com/api/episode/36',
        'https://rickandmortyapi.com/api/episode/38',
        'https://rickandmortyapi.com/api/episode/39',
        'https://rickandmortyapi.com/api/episode/40',
        'https://rickandmortyapi.com/api/episode/41',
        'https://rickandmortyapi.com/api/episode/42',
        'https://rickandmortyapi.com/api/episode/43',
        'https://rickandmortyapi.com/api/episode/44',
        'https://rickandmortyapi.com/api/episode/45',
        'https://rickandmortyapi.com/api/episode/46',
        'https://rickandmortyapi.com/api/episode/47',
        'https://rickandmortyapi.com/api/episode/48',
        'https://rickandmortyapi.com/api/episode/49',
        'https://rickandmortyapi.com/api/episode/51',
      ],
      url: 'https://rickandmortyapi.com/api/character/4',
      created: '2017-11-04T19:22:43.665Z',
    },
    {
      id: 5,
      name: 'Jerry Smith',
      status: 'Alive',
      species: 'Human',
      type: '',
      gender: 'Male',
      origin: {
        name: 'Earth (Replacement Dimension)',
        url: 'https://rickandmortyapi.com/api/location/20',
      },
      location: {
        name: 'Earth (Replacement Dimension)',
        url: 'https://rickandmortyapi.com/api/location/20',
      },
      image: 'https://rickandmortyapi.com/api/character/avatar/5.jpeg',
      episode: [
        'https://rickandmortyapi.com/api/episode/6',
        'https://rickandmortyapi.com/api/episode/7',
        'https://rickandmortyapi.com/api/episode/8',
        'https://rickandmortyapi.com/api/episode/9',
        'https://rickandmortyapi.com/api/episode/10',
        'https://rickandmortyapi.com/api/episode/11',
        'https://rickandmortyapi.com/api/episode/12',
        'https://rickandmortyapi.com/api/episode/13',
        'https://rickandmortyapi.com/api/episode/14',
        'https://rickandmortyapi.com/api/episode/15',
        'https://rickandmortyapi.com/api/episode/16',
        'https://rickandmortyapi.com/api/episode/18',
        'https://rickandmortyapi.com/api/episode/19',
        'https://rickandmortyapi.com/api/episode/20',
        'https://rickandmortyapi.com/api/episode/21',
        'https://rickandmortyapi.com/api/episode/22',
        'https://rickandmortyapi.com/api/episode/23',
        'https://rickandmortyapi.com/api/episode/26',
        'https://rickandmortyapi.com/api/episode/29',
        'https://rickandmortyapi.com/api/episode/30',
        'https://rickandmortyapi.com/api/episode/31',
        'https://rickandmortyapi.com/api/episode/32',
        'https://rickandmortyapi.com/api/episode/33',
        'https://rickandmortyapi.com/api/episode/35',
        'https://rickandmortyapi.com/api/episode/36',
        'https://rickandmortyapi.com/api/episode/38',
        'https://rickandmortyapi.com/api/episode/39',
        'https://rickandmortyapi.com/api/episode/40',
        'https://rickandmortyapi.com/api/episode/41',
        'https://rickandmortyapi.com/api/episode/42',
        'https://rickandmortyapi.com/api/episode/43',
        'https://rickandmortyapi.com/api/episode/44',
        'https://rickandmortyapi.com/api/episode/45',
        'https://rickandmortyapi.com/api/episode/46',
        'https://rickandmortyapi.com/api/episode/47',
        'https://rickandmortyapi.com/api/episode/48',
        'https://rickandmortyapi.com/api/episode/49',
        'https://rickandmortyapi.com/api/episode/50',
        'https://rickandmortyapi.com/api/episode/51',
      ],
      url: 'https://rickandmortyapi.com/api/character/5',
      created: '2017-11-04T19:26:56.301Z',
    },
  ],
};
